[package]
name = "starknet_hackathon"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.10.1"
openzeppelin_token = "1.0.0"

[dev-dependencies]
snforge_std = "0.31.0"

[[target.starknet-contract]]
name = "starknet_hackathon"
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"

[tool.fmt]
sort-module-level-items = true

[scripts]
test = "snforge test"